name: Build Teonet C library and create ded and rpm packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup Build essential
        run: sudo apt update && sudo apt install build-essential

      - name: Build Teonet C library and examples
        run: make build

      - name: Setut nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Build rpm package
        run: nfpm pkg --packager rpm --target ./

      - name: Build deb package
        run: nfpm pkg --packager deb --target ./

